version: '3.8'

services:
  db:
    image: postgres:14.3
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data

